# [Julia Programming: The Basic](https://www.youtube.com/playlist?list=PLeo1K3hjS3uvHr7N7j3GcMj48SdiTa_19)

# variable

In [1]:
a = "α"

"α"

In [3]:
typeof(a)

String

In [2]:
b = 2

2

In [4]:
typeof(b)

Int64

In [5]:
b = "str"

"str"

In [6]:
typeof(b)

String

In [7]:
pi

π = 3.1415926535897...

# Numbers

Two types of numbers
- integers
- float

In [8]:
a = 1
typeof(a)

Int64

In [9]:
a = 1.0
typeof(a)

Float64

In [18]:
println(11 / 4)
println(11 % 4)
println(div(11, 4))

2.75
3
2


In [24]:
println(bits(3))
println(bits(5))
println(bits(3 & 5))
println(bits(3 | 5))

0000000000000000000000000000000000000000000000000000000000000011
0000000000000000000000000000000000000000000000000000000000000101
0000000000000000000000000000000000000000000000000000000000000001
0000000000000000000000000000000000000000000000000000000000000111


In [26]:
println(3 & 5)
println(3 | 5)

1
7


In [29]:
println(bits(6))
println(bits(6 >> 1))
println(bits(6 << 1))

0000000000000000000000000000000000000000000000000000000000000110
0000000000000000000000000000000000000000000000000000000000000011
0000000000000000000000000000000000000000000000000000000000001100


In [33]:
println(typemax(Int64))
println(typemin(Int64))
println(typemax(Float64))
println(typemin(Float64))

9223372036854775807
-9223372036854775808
Inf
-Inf


In [34]:
1/0

Inf

In [35]:
0/0 # NAN: Not a number

NaN

$2x^2 - 3x + 1$

In [36]:
x = 1
println(2 * x^2 - 2 * x + 1)
println(2x^2 - 2x + 1)

1
1


# Complex and Rational Numbers

In [40]:
x = 3 + 4im
typeof(x)

Complex{Int64}

In [41]:
imag(x)

4

In [42]:
real(x)

3

In [43]:
abs(x)

5.0

In [44]:
angle(x)

0.9272952180016122

In [45]:
println((3 + 4im) + (2 + 5im))
println((3 + 4im) * (2 + 5im))

5 + 9im
-14 + 23im


rational number

In [47]:
x = 2 // 3
typeof(x)

Rational{Int64}

In [49]:
numerator(x)

2

In [50]:
denominator(x)

3

In [51]:
4//6

2//3

In [52]:
2//3 == 4//6

true

In [53]:
float(1//3)

0.3333333333333333

# String

- Characters
- Strings Intro
- Range indexing
- Unicode and UTF8
- String operations

In [54]:
'A'

'A': ASCII/Unicode U+0041 (category Lu: Letter, uppercase)

In [58]:
'a'

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [59]:
'α'

'α': Unicode U+03b1 (category Ll: Letter, lowercase)

In [55]:
typeof('A')

Char

In [56]:
'\u0958'

'क़': Unicode U+0958 (category Lo: Letter, other)

In [57]:
typeof('\u0958')

Char

In [61]:
Int('A')

65

In [62]:
Char(65)

'A': ASCII/Unicode U+0041 (category Lu: Letter, uppercase)

In [63]:
'A' < 'B'

true

In [64]:
'A' > 'B'

false

In [65]:
'A' < 'B' < 'C'

true

In [66]:
'A' < 'B' > 'C'

false

### String

In [68]:
"ice cream"

"ice cream"

index start from 1

In [69]:
text = "ice cream"

"ice cream"

In [70]:
text[0]

LoadError: BoundsError: attempt to access "ice cream"
  at index [0]

In [71]:
text[1]

'i': ASCII/Unicode U+0069 (category Ll: Letter, lowercase)

In [72]:
text[end]

'm': ASCII/Unicode U+006d (category Ll: Letter, lowercase)

In [75]:
text[end - 1]

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [74]:
text[-1]

LoadError: BoundsError: attempt to access "ice cream"
  at index [-1]

In [76]:
text[1:3]

"ice"

In [78]:
text[4:]

LoadError: syntax: missing last argument in "4:" range expression 

In [79]:
text[4:end]

" cream"

In [80]:
text[:3]

'e': ASCII/Unicode U+0065 (category Ll: Letter, lowercase)

In [82]:
typeof(text)

String

In [85]:
"AB"

"AB"

In [83]:
typeof("AB")

String

In [86]:
"哈哈"

"哈哈"

In [84]:
typeof("哈哈")

String

In [88]:
"I \u2665 you"

"I ♥ you"

In [89]:
string("First", "Second")

"FirstSecond"

In [90]:
a = "Hey"
b = "you"

"you"

In [91]:
a + b

LoadError: MethodError: no method matching +(::String, ::String)
Closest candidates are:
  +(::Any, ::Any, ::Any, ::Any...) at operators.jl:424

In [92]:
"$a $b"

"Hey you"

In [93]:
c = 5

5

In [94]:
"$a $b $c"

"Hey you 5"

# array

In [95]:
d = [1, 2, 3]

3-element Array{Int64,1}:
 1
 2
 3

In [97]:
"$a $d"

"Hey [1, 2, 3]"

In [98]:
search("love", 'o')

2

In [99]:
search("love", "ve")

3:4

In [100]:
"love"[search("love", "ve")]

"ve"

In [101]:
contains("love", 'l')

LoadError: MethodError: no method matching contains(::String, ::Char)
Closest candidates are:
  contains(::Function, ::Any, ::Any) at reduce.jl:664
  contains(::AbstractString, ::AbstractString) at strings/search.jl:378
  contains(::AbstractString, ::Regex) at /home/clint/.julia/v0.6/Compat/src/Compat.jl:1197

In [102]:
# substring search
contains("love", "l")

true

In [103]:
contains("I love Julia", "love")

true

In [104]:
contains("I love Julia", "loe")

false

# [Functions](https://www.youtube.com/watch?v=jHooi6KKrj0&index=6&list=PLeo1K3hjS3uvHr7N7j3GcMj48SdiTa_19)

- Function introduction
- Return multiple values
- operators are functions
- map function
- optional arguments
- keyword arguments

In [1]:
function f(x, y)
    return x + y
end

f (generic function with 1 method)

In [2]:
f(2, 3)

5

In [3]:
# this will also create a function
# this compact way of writing is suitable for small function
f(x, y) = x + y

f (generic function with 1 method)

even if you do not return a value, it also execute the function body and return a value

In [4]:
function f(x, y)
    x + y
end

f (generic function with 1 method)

In [5]:
f(2, 3)

5

what if....

In [6]:
function f(x, y)
    return x + y
    x * y
end

f (generic function with 1 method)

In [7]:
f(2, 3)

5

This behavior is similar to R

In [8]:
function f(x, y)
    x + y
    x * y
end

f (generic function with 1 method)

In [9]:
f(2, 3)

6

### Return multiple values

In [10]:
function f(a, b)
    a + b, a * b
end

f (generic function with 1 method)

In [12]:
f(3, 4) # it returns a tuple

(7, 12)

In [13]:
typeof(f(3, 4))

Tuple{Int64,Int64}

like python, you can 

In [14]:
x, y = f(3, 4)
println(x)
println(y)

7
12


### operators are functions

In [15]:
1 + 2 + 3

6

In [16]:
+(1, 2, 3)

6

Functiopns are first class object in Julia. Therefore, you can assign function to a varialbe

In [17]:
foo = +
foo(1, 2, 3)

6

In [18]:
function f(x, y)
    x + y
end

f (generic function with 1 method)

In [19]:
g = f

f (generic function with 1 method)

In [20]:
g(2, 3)

5

### map function
map function example below shows how function can be passed as an argument to another function

In [23]:
map(function(x) x^2 end, 
    [1, 2, 3])

3-element Array{Int64,1}:
 1
 4
 9

In [24]:
# a more compact way to write
map(x -> x^2, [1, 2, 3])

3-element Array{Int64,1}:
 1
 4
 9

### optional arguments

In [25]:
function f(x, y = 5)
    x + y
end

f (generic function with 2 methods)

In [26]:
f(2)

7

In [27]:
f(2, 3)

5

### Keyword arguments

In [28]:
function div(;x = 10, y = 5)
    x / y
end

div (generic function with 1 method)

In [29]:
div(x = 20, y = 10)

2.0

In [30]:
div(y = 10, x = 20)

2.0

# [If statement and ternary operator](https://www.youtube.com/watch?v=iHqWIDAjrG8&list=PLeo1K3hjS3uvHr7N7j3GcMj48SdiTa_19&index=7)

In [31]:
x = -1

-1

In [32]:
if x < 0
    print("negative")
else
    print("positive")
end

negative

In [34]:
function f(x)
    if x < 0
        print("negative")
    else
        print("positive")
    end
end

f (generic function with 2 methods)

In [35]:
f(-1)

negative

In [36]:
f(5)

positive

In [37]:
function f(x)
    if x < 0
        print("negative")
    elseif x > 0
        print("positive")
    else
        print("zero")
    end
end

f (generic function with 2 methods)

In [38]:
f(-1)

negative

In [39]:
f(5)

positive

In [40]:
f(0)

zero

### Ternary operator

In [41]:
print(x < 0 ? "negative" : "positive")

negative

# For while loop

- For loop
    - Iterate through an array
    - Iterate using range
- while
- continue
- break

In [43]:
for i in [1, 4, 7]
    println(i)
end

1
4
7


In [45]:
for i in [1, 4, 7] println(i) end

1
4
7


In [47]:
for s in ["John", "Benji", "Chris"]
    println(s, " Nice")
end

John Nice
Benji Nice
Chris Nice


In [48]:
for s in "John"
    println(s)
end

J
o
h
n


In [49]:
1:5

1:5

In [52]:
[1:5]

1-element Array{UnitRange{Int64},1}:
 1:5

In [50]:
for i = 1:5
    println(i)
end

1
2
3
4
5


In [51]:
for i in 1:5
    println(i)
end

1
2
3
4
5


### While loop

In [53]:
i = 1
while i <= 5
    println(i)
    i += 1
end

1
2
3
4
5


### Continue

In [56]:
for i in 1:5
    if i % 2 == 0
        continue
    end
    println(i)
end

1
3
5


### Break

In [57]:
key_location = "chair"

"chair"

In [58]:
for i in ["garage", "living room", "chair", "closet"]
    if i == key_location
        println("key found at ", i)
        break
    end
    println("key not found at ", i)
end

key not found at garage
key not found at living room
key found at chair


# Begin and ;

Sometimes it is convenient to have a single expression which evaluates several subexpressions in order, returning the value of the last subexpression as its value. There are two Julia constructs that accomplish this: begin blocks and (;) chains.

video link: https://www.youtube.com/watch?v=8j9jpHkE-4U&index=9&list=PLeo1K3hjS3uvHr7N7j3GcMj48SdiTa_19  
document: https://docs.julialang.org/en/stable/manual/control-flow/

In [60]:
area = begin
    base = 5
    height = 10
    (1 / 2) * base * height
end
print(area)

25.0

In [63]:
area = (base = 5 ; height = 10 ; (1 / 2) * base * height)
print(area)

25.0

In [64]:
function tri_area()
    base = 5
    height = 10
    (1 / 2) * base * height
end
area = tri_area()
print(area)

25.0

# Task (aka Generators & Coroutines)

`produce` in Julia is like `yield` in python  
`consume` in Julia is like `next` in python

Note: `consume` and `produce` is deprecated; use `channels` instead

In [65]:
function fib()
    a = 0
    produce(a)
    b = 1
    produce(b)
    while true
        a, b = b, a + b
        produce(b)
    end
end

fib (generic function with 1 method)

In [70]:
generator = Task(fib)

Task (runnable) @0x00007f3b1ae9ef50

In [76]:
consume(generator)

Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:70
 [2] consume(::Task) at ./deprecated.jl:955
 [3] include_string(::String, ::String) at ./loading.jl:522
 [4] execute_request(::ZMQ.Socket, ::IJulia.Msg) at /home/clint/.julia/v0.6/IJulia/src/execute_request.jl:158
 [5] (::Compat.#inner#17{Array{Any,1},IJulia.#execute_request,Tuple{ZMQ.Socket,IJulia.Msg}})() at /home/clint/.julia/v0.6/Compat/src/Compat.jl:385
 [6] eventloop(::ZMQ.Socket) at /home/clint/.julia/v0.6/IJulia/src/eventloop.jl:8
 [7] (::IJulia.##14#17)() at ./task.jl:335
while loading In[76], in expression starting on line 1
Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:70
 [2] produce(::Int64) at ./deprecated.jl:909
 [3] fib() at ./In[65]:8
while loading In[76], in expression starting on line 1


5

In [77]:
for num in Task(fib)
    if num > 13
        break
    end
    println(num)
end

0
1
1
2
3
5
8
13


Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:70
 [2] start at ./deprecated.jl:986 [inlined]
 [3] anonymous at ./<missing>:?
 [4] include_string(::String, ::String) at ./loading.jl:522
 [5] execute_request(::ZMQ.Socket, ::IJulia.Msg) at /home/clint/.julia/v0.6/IJulia/src/execute_request.jl:158
 [6] (::Compat.#inner#17{Array{Any,1},IJulia.#execute_request,Tuple{ZMQ.Socket,IJulia.Msg}})() at /home/clint/.julia/v0.6/Compat/src/Compat.jl:385
 [7] eventloop(::ZMQ.Socket) at /home/clint/.julia/v0.6/IJulia/src/eventloop.jl:8
 [8] (::IJulia.##14#17)() at ./task.jl:335
while loading In[77], in expression starting on line 1
Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:70
 [2] consume(::Task) at ./deprecated.jl:955
 [3] done at ./deprecated.jl:992 [inlined]
 [4] anonymous at ./<missing>:?
 [5] include_string(::String, ::String) at ./loading.jl:522
 [6] execute_request(::ZMQ.Socket, ::IJulia.Msg) at /home/clint/.julia/v0.6/IJulia/src/execute_request.jl:158
 [7]

if you want to pass argument in side the generator function, use `@task`

In [78]:
function fib(msg)
    println(msg)
    a = 0
    produce(a)
    b = 1
    produce(b)
    while true
        a, b = b, a + b
        produce(b)
    end
end

fib (generic function with 2 methods)

In [79]:
generator = @task fib("hello world")

Task (runnable) @0x00007f3b1ae12230

In [80]:
consume(generator)

hello world


Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:70
 [2] consume(::Task) at ./deprecated.jl:955
 [3] include_string(::String, ::String) at ./loading.jl:522
 [4] execute_request(::ZMQ.Socket, ::IJulia.Msg) at /home/clint/.julia/v0.6/IJulia/src/execute_request.jl:158
 [5] (::Compat.#inner#17{Array{Any,1},IJulia.#execute_request,Tuple{ZMQ.Socket,IJulia.Msg}})() at /home/clint/.julia/v0.6/Compat/src/Compat.jl:385
 [6] eventloop(::ZMQ.Socket) at /home/clint/.julia/v0.6/IJulia/src/eventloop.jl:8
 [7] (::IJulia.##14#17)() at ./task.jl:335
while loading In[80], in expression starting on line 1
Stacktrace:
 [1] depwarn(::String, ::Symbol) at ./deprecated.jl:70
 [2] produce(::Int64) at ./deprecated.jl:909
 [3] fib(::String) at ./In[78]:4
 [4] (::##10#11)() at ./task.jl:80
while loading In[80], in expression starting on line 1


0

since those are deprecated, lets try channels  
https://discourse.julialang.org/t/how-to-replace-consume-and-produce-with-channels/5125  
https://discourse.julialang.org/t/tasks-and-type-stability/3212  

# Exception Handling

In [82]:
try 
    sqrt(-1)
catch
    println("Exception Occured")
end

Exception Occured


In [83]:
try 
    sqrt(-1)
catch y
    println("Exception Occured: ", y)
end

Exception Occured: DomainError()
